### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by HunterTheCoder123** [Asgarrrr/Luna#23]
So I'm getting an error like:
"Invalid oauth2 redirect_uri"
Please, help me.

**Comment by Asgarrrr** [comment]
Hello, the dashboard is just the beginning for now.

However, for your problem, it's quite normal, because the dashboard is not working, I didn't do the documentation. You have to go to the `OAuth2` section, then enter these urls (change the port according to yours)
<img width="335" alt="Capture d’écran 2021-03-06 à 10 21 05" src="https://user-images.githubusercontent.com/36574651/110201967-2821cd80-7e66-11eb-9218-7d66e52f4397.png">
<img width="1056" alt="Capture d’écran 2021-03-06 à 10 21 19" src="https://user-images.githubusercontent.com/36574651/110201968-28ba6400-7e66-11eb-9914-0e2c610c2ac1.png">
